services:
    sogevia_form.form_handler:
        class: Sogevia\Component\Form\FormHandler

    sogevia_form.confirm.form_type:
        class: Sogevia\Component\Form\Type\ConfirmType
        tags:
            - { name: "form.type", alias: "sogevia_confirm_type" }

    sogevia_form.boolean.form_type:
        class: Sogevia\Component\Form\Type\BooleanType
        tags:
            - { name: "form.type", alias: "boolean" }

